### ISSUE TITLE
Fix Failing Test - top_bookmarks

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu-ecosystem/Zeeguu-API#299]
- The `top_bookmarks` in `top_bookmarks_for_user.py` should return bookmarks that are are in learning, rather than learned.

This was introduced with the changes to using the `learned_time`, when replacing I mistakenly thought it was for learned bookmarks.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the top_bookmarks function in zeeguu/core/bookmark_quality/top_bookmarks_for_user.py to return bookmarks that are in learning rather than learned. This is done by changing the filter condition from Bookmark.learned_time != None to Bookmark.learned_time == None.

You can review changes in this commit: https://github.com/lattaai12/zeeguu-api-299/commit/a5f8ffbb81eadd3fb3de02e2505a159b49a2bd26.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
