### ISSUE TITLE
create_cohort API problem

### ISSUE THREAD

**Issue by mbrodt** [zeeguu-ecosystem/Zeeguu-API#41]
I had some problems posting JSON data from a React front end to the API. The request was posted from the front end with the correct data for creating a new cohort, but the API considered the request to be empty. I can fix this by using the "get_json()" function in the API, but this breaks the tests and might break other consumers of the API. 
Change:
inv_code = request.form.get("inv_code")
name = request.form.get("name")
language_id = request.form.get("language_id")
max_students = request.form.get("max_students")

To:
inv_code = request.get_json()["form"]["inv_code"]
name = request.get_json()["form"]["name"]
language_id = request.get_json()["form"]["language_id"]
max_students = request.get_json()["form"]["max_students"]

Any suggestions for how to deal with this?

**Comment by mircealungu** [comment]
did you test the API with Postman? do you have the same problem?
do you have the same problem with other endpoints? 
could it be that react sets the mime type to "application/json" which is different for the ajax calls that the current Teacher Dashboard uses? if this is correct, i'd rather change that. 

otherwise you can make the proposed change but then you have to change also the current teacher dashboard content. we should keep the two frontends working in parallel before we switch from one to the other!

**Comment by mbrodt** [comment]
All good points - I'll try testing out some other endpoints and using Postman and then report back.

**Comment by mbrodt** [comment]
You are correct - the API accepts the data in a "form-data" format. So on the client, I needed to put my data inside a FormData() object and send that to the server and now it works :)
