### ISSUE TITLE
Independent removal of classes and texts 

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Zeeguu-API#60]
Two endpoints need to be modified to allow removal of classes and texts without the need of unattaching texts from classes and classes from texts: 

- "delete_own_text"
- "/remove_cohort/${cohortID}"

**Comment by mircealungu** [comment]
Question about delete_own_text
- should the text disappear from all the cohorts if I delete it? 
- but it should still remain in the DB for the sake of the students who read it and and in their history. one question would be: if I published the article, and I deleted it after; should I still be listed as an author/uploaded? I guess I should. It was my who uploaded it for people to read. I'm asking this because this will have an impact on the DB implementation of this.

**Comment by SaraTolstrupHusum** [comment]
1) Are teachers aware that they can share classes like that? I don't think, they are. But none-the-less, imo it would be a nice feature, if classes can stay visible in "My classes" to any teacher associated with the class - regardless of who created it. So that they each have to delete it from their individual list of classes if and when they each no longer want it. And then if no teachers want a class, it is actually deleted from the db.

2) If a teacher deletes a text, it should disappear from all classes, yes. (The exception being that it should still be visible to active students who has already read the text.) If no active student has read the text... It should be completely deleted.

3) As it is the teacher who writes/uploads the text and that he/she has to confirm that we can still show it to the students who had read it before the deletion. I see no problem in them staying named author/uploader.

**Comment by eleonora-k** [comment]
1. We will rename the feature to "Remove from list", because "Hide" or "Archive" means that there is a place where the class can be returned back to the list of classes and that is not the case.
2. Yes.
3. Let's not go down this path. The teacher will be the author and we will implement 1 and 2 :)

**Comment by SaraTolstrupHusum** [comment]
Delete_own_texts has been fixed on the backend. We need to add guidance to the teachers that they cannot delete a text that is shared with classes.
@mircealungu: We still need to be able to remove classes without first unattaching them from all texts. (See answers to questions above)

**Comment by mircealungu** [comment]
this is fixed now: classes can be deleted w/o the need to detach the texts from them first.
