### ISSUE TITLE
add getStudentActivityOverview endpoint

### ISSUE THREAD

**Issue by majapetersen** [zeeguu-ecosystem/Zeeguu-API#64]
"getStudentActivityOverview" object should contain:

- numberOfReadTexts
- numberOfExercisesDone
- readingTimeSpent
- exerciseTimeSpent
- averageTextLength
- averageTextLevel
- ExerciseCorrectness

api.getStudentActivityOverview(studentID, cohortID, duration) - returns list if "studentActivityOverview" objects of the collected reading and exercise data from each student within the time period.

**Comment by mircealungu** [comment]
Implemented at: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/d3e5db3a317ca7bfb2e5941a23bb8e2997af7efc/zeeguu_api/api/teacher_dashboard/student.py#L94

Observations: 
* number of read texts - we don't have a good definition of "read text" actually. Opened articles would be more correct. Read... we don't know if they really read it all. Do you see what I mean? 
* numberOfExercisesDone --  The UI talks about "exercise sessions completed". However,  you're more correct here. It's safer to talk about "exercises done" rather than sessions completed. They can start a session and not finish.

**Comment by SaraTolstrupHusum** [comment]
re 1) Would it be an option to set a lower bound of say 200 words pr minute and assume that a text is "read" if the student's reading time is such that: textLength/readingTime>200?

re 2) Already added it to our ToDo. ;)

**Comment by majapetersen** [comment]
@mircealungu We are missing the res for numberOfExercisesDone, can you please add this res to this endpoint. Thank you 👍

**Comment by majapetersen** [comment]
@mircealungu We found the data for "exercisesDone" in the data, but because it is not stated in the return example (see attached) we did not see it :-) 
![185044430_836656623934101_5576694189107336429_n](https://user-images.githubusercontent.com/72250688/117947944-f53a0100-b310-11eb-905c-e5583a1054ef.png)

**Comment by mircealungu** [comment]
Ah!
Thanks for finding it. 
And for spotting one of the eternal problems with the documentation. It always becomes outdated :)
M.

**Comment by majapetersen** [comment]
@mircealungu - As we talked about today we are having difficulties figuring out if the missing and inconsistent data is backend or frontend related. 

Also we have created the "Mircea task" label for you :-) 

[
<img width="640" alt="PastedGraphic-14" src="https://user-images.githubusercontent.com/72250688/118146093-8e027680-b40e-11eb-956c-ec32f76a44ba.png">
](url)

**Comment by mircealungu** [comment]
Seems to be fixed after all? 

![image](https://user-images.githubusercontent.com/464519/118152067-f8baae80-b41c-11eb-8bf8-7915f8f65d9a.png)

**Comment by mircealungu** [comment]
if you encounter the problem again let me know :)

**Comment by mircealungu** [comment]
but i seem to be able to identify a problem with the UI by:
- looking at the DoNotDeleteClass
- selecting 1 year
- then selecting 1 week
- you see that the same students have bars as the ones that had data in 1 year
- then refresh the page
- now I see full exercises bars for all the students.

**Comment by SaraTolstrupHusum** [comment]
The problem mentioned above have been fixed, but there is another problem (copied comment from Eleonora i a related issue in her to keep everything in one place:

> We have discovered an inconsistency in reading time presented in the class overview and then in reading activity for a student. For example, in the class overview of DoNotDeleteClass, when selecting activity for 1 year, user sara2 has 10 minutes of reading, and when summarizing the minutes she spent on reading each article, we get 14 minutes. Do you know what could be causing this? Can it be a rounding issue somewhere?

Also, after looking closely at it, I realized that the student object contains correct reading_time and exercises_done, but direct data we get about readingTime and exerciseTIme is not.
It's the api.getStudentActivityOverview causing inconsistency. I have changed the progress bar to depend on the reading and exercise time of the student object, and it's presented properly now on my branch, but the information about number of articles and number of exercises is incorrect, f.x., it is showing that users who read for 20 minutes have read 0 texts.

**Comment by mircealungu** [comment]
Hmm. At a first glance it seems that : 

1. the /student_activity_overview endpoint depends on `summarize_reading_activity` which computes the time *in the language of the cohort*. 
2. the /user_info/<id>/<duration> endpoint depends on `info_for_teacher_dashboard` (the older implementation) which sums up all the reading sessions, independent of the cohort language (so for sara, this includes some Spanish texts even if we're looking at the English cohort.

Could this be the case? 

Because then i'd say we use the first one and drop the second one. It's also better named, it's probably faster. Only that you might need some more information in there?

**Comment by SaraTolstrupHusum** [comment]
Agreed , that it would make sense to only include the data about activities _in the cohort language_  but I still don't think this data is consistent with the reading time that we get from: /users_from_cohort. Is it?

**Comment by mircealungu** [comment]
Oh. I'll look again at this tomorrow at the latest.

**Comment by eleonora-k** [comment]
@mircealungu are there any news on this one? :)

**Comment by mircealungu** [comment]
I LIKE THIS MESSAGE :)

![image](https://user-images.githubusercontent.com/464519/121251340-0d1c8a80-c8a7-11eb-90f3-a3379fd1e44a.png)

**Comment by mircealungu** [comment]
the "in English" is important info! nice.

**Comment by mircealungu** [comment]
ok. 

regarding your question, indeed, there is some **very generous** conversion being done by the UI (code you inherited?) that rounds up to the minute the duration of the reading session in returned by the /student_reading_sessions endpoint. e.g. in the image, you see 10sec being converted to 1min. 

![image](https://user-images.githubusercontent.com/464519/121253069-f840f680-c8a8-11eb-813b-e9703adf8a9e.png)

**Comment by mircealungu** [comment]
the durations for the sara2 add up nicely to the 586s returned by the /student_activity_overview.

![image](https://user-images.githubusercontent.com/464519/121253486-756c6b80-c8a9-11eb-93f1-27064b158df7.png)

**Comment by SaraTolstrupHusum** [comment]
@mircealungu 
The UI conversions are indeed both generous and inherited. We will fix that part no worries.
It also seems very plausible, that the reason for the inconsistencies are due to the /student_activity_overview endpoint computing the time _in the language of the cohort_ while the other endpoints just compute _reading time in all languages_.
However, it is not the /user_info/<id>/<duration> causing the problem. It is the /users_from_cohort/<cohortID>/<duration> that we are calling to set the list of students, that we show to the teacher for each class.
Using the /student_activity_overview instead of /users_from_cohort/<cohortID>/<duration> seems difficult as the former returns data on one student while the latter returns a list of the students in the cohort.
So could we change the reading_time, exercise_done and total_time for each student returned by /users_from_cohort/<cohortID>/<duration> to just be the time related to the language of the cohort?

**Comment by mircealungu** [comment]
@SaraTolstrupHusum 

> So could we change the reading_time, exercise_done and total_time for each student returned by /users_from_cohort// to just be the time related to the language of the cohort?

What is `total_time`? I don't think it's returned in `users_from_cohort`? 

Also, I see that currently the `/users_from_cohort` returns something like `reading_time_list` and `exercise_time_list`. Am I correct to understand that this is not going to be needed? I can simplify the `/users_from_cohort` in that case.

**Comment by mircealungu** [comment]
@SaraTolstrupHusum 

also, we have to update `user_info` and `cohort_member_bookmarks` to take also the cohort as input. 
do you depend on both of these? 

I'll mark the current GET endpoints as deprecated, and add ones with POST instead.

**Comment by mircealungu** [comment]
So something like this from /users_from_cohort? 

```
[
{"id": 2694, "name": "ruben", "email": "rubenrien@gmail.com", "number_of_texts": 0, "reading_time": 0,
"average_text_length": 0, "average_text_difficulty": 0, "exercise_time_in_sec": 0, "exercise_time": 0,
"correct_on_1st_try": "0", "number_of_exercises": 0}
]
```

**Comment by SaraTolstrupHusum** [comment]
@mircealungu
The above looks good I think. I will try  to implement it later.
The total time is computed by us, so no worries there.
Will check about dependencies on  `user_info` and `cohort_member_bookmarks` and use  `exercise_time` instead of the `...in_sec` option.
Will let you know if anything doesn't work.

**Comment by mircealungu** [comment]
Cool. I've just deployed this new version.

**Comment by SaraTolstrupHusum** [comment]
We do have dependencies on `user_info` but not `cohort_member_bookmarks`. Can you link to the implementation of `user_info` here so I won't have to guess the syntax?

**Comment by mircealungu** [comment]
Good question!

Here's the link:
https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/9e00d3ebebb117d87c7f57a919c854430e2f98d0/zeeguu_api/api/teacher_dashboard/student.py#L33

You'll see that it extracts it's necessary data with the use of `_get_student_cohort_and_period_from_POST_params` which expects the three POST parameters: 
https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/9e00d3ebebb117d87c7f57a919c854430e2f98d0/zeeguu_api/api/teacher_dashboard/_common_api_parameters.py#L25

I hope this is clear.

**Comment by SaraTolstrupHusum** [comment]
Works!
