### ISSUE TITLE
join_cohort(inviteCode, studentID) endpoint

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#68]
When a teacher removes a student from a cohort - currently the student has no way of joining another cohort or rejoining the old one. We need an endpoint: join_cohort(studentID, inviteCode) that allows this.

**Comment by mircealungu** [comment]
added here: https://github.com/zeeguu-ecosystem/Zeeguu-API/blob/f1727ea26f3839a321917e41323e3c86ad16101f/zeeguu_api/api/teacher_dashboard/student.py#L201

- note that it does not take the studentID because it assumes that it's being called by the logged in user. 

this also requires corresponding UI controls in the user settings I think, right?

**Comment by SaraTolstrupHusum** [comment]
We implemented the UI controls, and it works very well. If the endpoint returned the cohortID instead of just the "OK", we would be able to route even better, but that is a nice to have.

**Comment by mircealungu** [comment]
cool.

modified the result to return a JSON of the form {"cohort_id": 321}

**Comment by mircealungu** [comment]
I can also return the name of the cohort if you need it.

**Comment by SaraTolstrupHusum** [comment]
Nah, the cohortID is perfect.

**Comment by SaraTolstrupHusum** [comment]
Oh!!! Brainfart!!! The ID does not help us at all. We need the "OK". I will stop multitasking now.

**Comment by mircealungu** [comment]
changed to "ok" again.
