### ISSUE TITLE
text upload bug

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/Zeeguu-API#77]
The backend does not accept texts with the title "test1" but "test 1" is fine.
Why is this?

**Comment by mircealungu** [comment]
why would you want to upload a text with that title?!?
I have such a strong "dèja vu" now!

**Comment by SaraTolstrupHusum** [comment]
Godt ord igen! ;)

**Comment by mircealungu** [comment]
I could not replicate the problem with the two titles that you mention.
But it might be related to another bug? 
Sometimes when uploading a very small text the difficulty estimator would raise a division by zero. That would prevent the text from being saved. That bug is fixed now. Can you see whether it fixes also this issue?
