### ISSUE TITLE
Users cannot delete "old" classes

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu-ecosystem/zeeguu-api#83]
Users cannot delete cohorts created in the old teacher dashboard. - Why?
(Tested thoroughly with with Pernilles user.)
- suspecting it is because the "old" cohorts does not have the data required by the backend?

**Comment by mircealungu** [comment]
I'll look into it.

**Comment by mircealungu** [comment]
Fixed.

In the process I think created a new "feature" :)

- a teacher can delete a class even if that class still has texts and students associated with it; the students will be unenrolled; (this is not new I think); and the texts will be unliked from that class (this is the new part); so the teacher does not have to go and dis-associate them one by one.

One implication of this is that the message that appears in red about the failure to delete maybe being due to texts associated with the class does not make sense anymore.

**Comment by majapetersen** [comment]
This is really nice Mircea! Being able to delete a class without first having to disassociate all texts from that class is a huge improvement🙌🏼😊

**Comment by SaraTolstrupHusum** [comment]
This has been fixed ages ago.
